#!/usr/bin/env node
// 04-rfc-gen.cjs — Generate one RFC stub per MED+ gap. Stubs are idempotent:
// if an RFC for a given entity_id already exists, only mutable fields (disposition,
// reviewer, notes) are preserved; everything else is regenerated.
"use strict";

const fs = require("fs");
const path = require("path");
const crypto = require("crypto");
const { readSIJ, loadConfig, parseArgs } = require("./lib/sij.cjs");
const { RISK_LEVELS } = require("./lib/heuristics.cjs");

const MIN_RISK = "med"; // RFCs are required for med, high, critical

function rfcIdFor(entityId, gap) {
  const h = crypto.createHash("sha1").update(entityId + "::" + gap).digest("hex").slice(0, 8);
  return "RFC-" + h.toUpperCase();
}

function slugify(s) {
  return s.replace(/[^a-zA-Z0-9]+/g, "-").replace(/^-+|-+$/g, "").slice(0, 60);
}

function readExistingDisposition(filePath) {
  if (!fs.existsSync(filePath)) {
    return { disposition: "pending", reviewer: "", reviewed_at: "", notes: "" };
  }
  const raw = fs.readFileSync(filePath, "utf8");
  const fm = (raw.match(/^---\n([\s\S]*?)\n---/) || [, ""])[1];
  const o = { disposition: "pending", reviewer: "", reviewed_at: "", notes: "" };
  fm.split("\n").forEach((line) => {
    const m = line.match(/^(\w+):\s*(.*)$/);
    if (m && o.hasOwnProperty(m[1])) o[m[1]] = m[2].trim();
  });
  return o;
}

function renderRFC(rfcId, gap, disposition) {
  const title = `${gap.gap.toUpperCase()}: ${gap.name}`;
  const mono = gap.monolith ? `\`${gap.monolith.file}:${gap.monolith.line}\` — \`${gap.monolith.signature}\`` : "_not present_";
  const mod  = gap.modular  ? `\`${gap.modular.file}:${gap.modular.line}\` — \`${gap.modular.signature}\``  : "_not present_";
  const domain = (gap.monolith?.tags?.domain) || (gap.modular?.tags?.domain) || "unknown";
  const cabRequired = gap.risk === "high" || gap.risk === "critical";

  return `---
rfc_id: ${rfcId}
title: ${title}
entity_id: ${gap.entity_id}
gap: ${gap.gap}
risk: ${gap.risk}
domain: ${domain}
cab_required: ${cabRequired}
disposition: ${disposition.disposition}
reviewer: ${disposition.reviewer}
reviewed_at: ${disposition.reviewed_at}
notes: ${disposition.notes}
---

# ${rfcId} — ${title}

**Risk:** \`${gap.risk}\` &middot; **Domain:** \`${domain}\` &middot; **CAB required:** \`${cabRequired}\`

## What changed

> ${gap.notes}

## Anchors

- **Monolith:** ${mono}
- **Modular:** ${mod}

## Disposition options

Pick one and set in the front-matter \`disposition:\`:

- \`approved\` — Modular version is intentional and behavior-equivalent. **CAB passes.**
- \`intentional_drop\` — Monolith symbol was deliberately removed (deprecated, replaced by another mechanism). **Requires justification in \`notes\`.**
- \`intentional_rename\` — Symbol moved/renamed; map the equivalent under \`notes:\`. Pair this RFC with the "new" RFC for the renamed counterpart.
- \`regression_to_fix\` — This is a real regression. Block CAB until fixed. **Action item required.**
- \`rejected\` — RFC is invalid (false positive). **CAB ignores.**

## Verification

- [ ] Visual / behavioral test exercised on this surface
- [ ] No downstream importer broken (\`grep\` for usages)
- [ ] If \`approved\` or \`intentional_*\`: justification documented

---

_Generated by parity-cab. Re-running 04-rfc-gen.cjs preserves the \`disposition\`, \`reviewer\`, \`reviewed_at\`, and \`notes\` fields above._
`;
}

function main() {
  const args = parseArgs(process.argv.slice(2));
  const cfg = loadConfig(args.config || "parity.config.json");
  const report = readSIJ(path.join(cfg.out_dir, "parity-report.sij.json"));
  const rfcDir = path.join(cfg.out_dir, "rfcs");
  if (!fs.existsSync(rfcDir)) fs.mkdirSync(rfcDir, { recursive: true });

  const minIdx = RISK_LEVELS.indexOf(MIN_RISK);
  const eligible = report.entities.filter((g) => RISK_LEVELS.indexOf(g.risk) >= minIdx);

  let written = 0, preserved = 0;
  for (const gap of eligible) {
    const rfcId = rfcIdFor(gap.entity_id, gap.gap);
    const fileName = `${rfcId}-${slugify(gap.name)}-${gap.gap}.md`;
    const filePath = path.join(rfcDir, fileName);
    const existing = readExistingDisposition(filePath);
    if (existing.disposition !== "pending") preserved++;
    fs.writeFileSync(filePath, renderRFC(rfcId, gap, existing), "utf8");
    written++;
  }
  console.log(`[rfc-gen] ${written} RFC(s) written (${preserved} preserved disposition) → ${rfcDir}`);
  console.log(`[rfc-gen] eligible gaps: ${eligible.length} / ${report.entities.length} total`);
}

if (require.main === module) main();
