import { deriveStatuses, needsReview } from './state.mjs';

const arr = (v) => (Array.isArray(v) ? v : []);
const cell = (s) => String(s ?? '').replace(/\|/g, '\\|').replace(/\n/g, ' ');

export function ownerQuestions(snap) {
  const derived = deriveStatuses(snap.plan, snap.journal);
  return arr(snap.plan.tasks).filter(t => derived.get(t.id) === 'blocked').map(t => {
    const b = snap.journal.filter(e => e.task === t.id && e.type === 'block').pop();
    return { task: t, reason: b?.reason, question: b?.owner_question };
  });
}

export function nextAction(snap) {
  const derived = deriveStatuses(snap.plan, snap.journal);
  const tasks = arr(snap.plan.tasks);
  const active = tasks.find(t => derived.get(t.id) === 'active');
  if (active) return `continue ${active.id} "${active.title}" → make its acceptance checks pass, then \`mc verify ${active.id}\`${needsReview(active) ? ', review' : ''}, \`mc done ${active.id}\``;
  const ready = tasks.find(t => derived.get(t.id) === 'todo' && arr(t.depends_on).every(d => derived.get(d) === 'done'));
  if (ready) return `start ${ready.id} "${ready.title}" with \`mc start ${ready.id}\``;
  const q = ownerQuestions(snap).find(x => x.question);
  if (q) return `waiting on the owner for ${q.task.id}: ${q.question}`;
  return 'no ready work — plan the next milestone (docs/runbooks/planning.md)';
}

// Deterministic: derived only from control/ files, so gate D3 can compare byte-for-byte.
export function renderStatus(snap) {
  const { mission, plan, findings, journal } = snap;
  const derived = deriveStatuses(plan, journal);
  const tasks = arr(plan.tasks);
  const L = [];
  L.push('<!-- GENERATED by `node harness/mc.mjs render` from control/. Do not edit: gate D3 rejects drift. -->');
  L.push('# Macrofy — Status', '');
  L.push(`**Mission** (${mission.status}): ${mission.statement}`, '');
  L.push(`**Next action:** ${nextAction(snap)}`, '');
  L.push('## Goals', '', '| Goal | Title | Measure | Tasks done |', '|---|---|---|---|');
  for (const g of arr(mission.goals)) {
    const mine = tasks.filter(t => arr(t.goals).includes(g.id) && derived.get(t.id) !== 'dropped');
    L.push(`| ${g.id} | ${cell(g.title)} | ${cell(g.measure)} | ${mine.filter(t => derived.get(t.id) === 'done').length}/${mine.length} |`);
  }
  if (arr(mission.non_goals).length) L.push('', '**Non-goals:** ' + mission.non_goals.map(cell).join('; '));
  if (arr(mission.constraints).length) L.push('', '**Constraints:** ' + mission.constraints.map(cell).join('; '));
  L.push('', '## Milestones');
  for (const m of arr(plan.milestones)) {
    const mine = tasks.filter(t => t.milestone === m.id);
    const live = mine.filter(t => derived.get(t.id) !== 'dropped');
    L.push('', `### ${m.id} — ${m.title} (${live.filter(t => derived.get(t.id) === 'done').length}/${live.length} done)`, '');
    L.push('| Task | Title | Status | Goals | Depends on | Review | Spec |', '|---|---|---|---|---|---|---|');
    for (const t of mine) L.push(`| ${t.id} | ${cell(t.title)} | ${derived.get(t.id)} | ${arr(t.goals).join(', ')} | ${arr(t.depends_on).join(', ') || '—'} | ${needsReview(t) ? 'required' : 'optional'} | ${t.spec ? `[spec](${t.spec.replace(/^docs\//, '')})` : '—'} |`);
  }
  L.push('', '## Waiting on the owner', '');
  const qs = ownerQuestions(snap);
  L.push(...(qs.length ? qs.map(q => `- **${q.task.id}** — ${cell(q.question || q.reason)}`) : ['- nothing']));
  L.push('', '## Open findings', '');
  const open = arr(findings.findings).filter(f => f.status === 'open');
  L.push(...(open.length ? open.map(f => `- **${f.id}** [${f.severity}] ${cell(f.title)}${arr(f.expected_failing).length ? ` (expected failing: ${f.expected_failing.join(', ')})` : ''}`) : ['- none']));
  const amends = journal.filter(e => e.type === 'amend');
  if (amends.length) L.push('', '## Criteria amendments (owner should review)', '', ...amends.map(e => `- #${e.seq} ${e.task} by ${e.by}: ${cell(e.reason)}`));
  L.push('', '## Recent handoffs', '');
  const notes = journal.filter(e => e.type === 'note').slice(-5).reverse();
  L.push(...(notes.length ? notes.map(e => `- #${e.seq} ${e.at.slice(0, 10)} (${e.by}): ${cell(e.text)}`) : ['- none']));
  return L.join('\n') + '\n';
}

export function renderBrief(snap, gateResults) {
  const { mission, plan, journal } = snap;
  const derived = deriveStatuses(plan, journal);
  const tasks = arr(plan.tasks);
  const count = (s) => tasks.filter(t => derived.get(t.id) === s).length;
  const failed = gateResults.filter(r => !r.ok);
  const L = [];
  L.push('MACROFY MISSION CONTROL — brief');
  L.push(`Mission (${mission.status}): ${mission.statement}`);
  L.push(`Goals: ${arr(mission.goals).map(g => `${g.id} ${g.title}`).join(' | ')}`);
  L.push(`Tasks: ${count('done')} done, ${count('active')} active, ${count('todo')} todo, ${count('blocked')} blocked`);
  for (const q of ownerQuestions(snap)) L.push(`Blocked ${q.task.id}: ${q.question ? `OWNER QUESTION — ${q.question}` : q.reason}`);
  const last = journal.filter(e => e.type === 'note').pop();
  if (last) L.push(`Last handoff (#${last.seq}, ${last.by}): ${last.text}`);
  L.push(`Gates (fast): ${failed.length ? `FAIL — ${failed.map(r => r.id).join(', ')} (run \`node harness/mc.mjs check --fast\`)` : 'PASS'}`);
  L.push(`NEXT: ${nextAction(snap)}`);
  L.push('Protocol: one task at a time — start → build → verify → review → done → note. Details: macrofy/AGENTS.md');
  return L.join('\n');
}
